permissions:
  contents: write
  packages: write
  id-token: write

name: release
on:
  push:
    tags:
    - v*.*.*
    - '!v*.*.*-**'

jobs:    
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ko-build/setup-ko@v0.8
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}